title: Lorenzo Lazzari # your name (or website title) here
logo: "/images/profile_new.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pursuing a M.Sc. in Statistics with a focus on Data Science
  <br><br>
  <img src="https://llazzar.github.io/datascience-portfolio/icon/linkedin.png" width="14" height="14"> 
  <a href="https://www.linkedin.com/in/lorenzo-lazzari-869026232/">LinkedIn</a>
  <br>
  <img src="https://llazzar.github.io/datascience-portfolio/icon/cv.png" width="14" height="14"> 
  <a href="/datascience-portfolio/documents/lorenzo_lazzari_cv.pdf">CV/Resumé</a>
  <br>
  <img src="https://lazzar.github.io/datascience-portfolio/icon/github.png" width="14" height="14"> 
  <a href="https://github.com/lorenzolazzari98">Github</a>
  <br>
  <img src="https://llazzar.github.io/datascience-portfolio/icon/kaggle.png" width="14" height="14"> 
  <a href="https://www.kaggle.com/lorenzolazzari">Kaggle</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
