title: Lorenzo Lazzari # your name (or website title) here
logo: "/images/profile.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Pursuing a M.Sc. in Statistics with a curriculum in Data Science
  <br><br>
  Second description 
  <br><br>
  <img src="/datascience-portfolio/icon/linkedin.png><a href="https://www.linkedin.com/in/lorenzo-lazzari-869026232/">LinkedIn Profile</a>
  <br>
  <a href="/datascience-portfolio/documents/cv_lorenzo_lazzari1.pdf">Resume</a> 
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
